defaults:
  - trainer: default.yaml
  - datamodule: datamodule.yaml
  - model: net.yaml
  - logger: wandb.yaml
  - hydra: default.yaml
  - _self_

work_dir: ${hydra:runtime.cwd}
data_dir: /opt/ml/data/
val_check_interval: 1
lr_log_interval: 'step'
# path to folder with data
run_id: null